version: 7
preset: psr2
risky: false

tab-width: 4
use-tabs: true

enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array

finder:
  path:
    - qa-src
    - qa-include
  not-path:
    - qa-include/vendor
